#!/bin/bash
echo "*******-Starting CI CD Pipeline Tasks-*******"
#BUILD
echo ""
echo "..... Build Phase Started :: Compiling Source Code :: ......"
cd java_web_code
mvn install

#-BUILD (TEST)
echo ""
echo "..... Test Phase Started .. Testing via Automated Scrints :: ......"
cd ../integration-testing/
mvn clean verify -P integration-test
